### ISSUE TITLE
Can not spawn /var/run/sharkd.sock on a container

### ISSUE THREAD

**Issue by codezgitz** [QXIP/webshark#15]
Hello. First of all , Thanks for the work you have done in this repo. 

I am trying to run the node application in a docker container . I am facing issues as spawning to /var/run/sharkd.sock is not working If I set SHARKD_SOCKET = "/var/run/sharkd.sock". I am getting following error - 

`Error trying to connect to /var/run/sharkd.sock
Error: connect ENOENT /var/run/sharkd.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/sharkd.sock'
}
`

/var/run is already mounted so that should not be any issue. I have docker.sock inside /var/run folder . I gave a try by setting SHARKD_SOCKET = "/var/run/docker.sock" . Then I didn't get ENOENT error but `new_sock.write(JSON.stringify(request)+"\n")` did not work. So I am thinking spawning `unix:/var/run/sharkd.sock` is the actual issue in container. 

Sharkd is running by `sharkd - unix:/var/run/sharkd.sock`. I can see 'Hello in child' output in the terminal

Could you please point me out if I am missing something.

**Comment by lmangani** [comment]
Resolved in the latest version. In case of doubt store the socket inside the /capture folder
