### ISSUE TITLE
Extraneous files in repo

### ISSUE THREAD

**Issue by ekoyle** [QXIP/webshark#18]
I've noticed some extraneous/old files in the repository.  Does anyone have a problem with deleting the following? I think they could lead to confusion down the road.

 * `web/js/webshark-app.js` - generated from other files, probably shouldn't be under version control
 *  `sharkd/*` with the exception of `sharkd/build.sh` - shouldn't be needed since we only use the wireshark repo

**Comment by lmangani** [comment]
@ekoyle go ahead we can validate this all in parallel
