### ISSUE TITLE
uploading error

### ISSUE THREAD

**Issue by shuimoshusheng** [QXIP/webshark#32]
After uploading the pcapfile, it was not stored in the specified mapped captures folder, so the web file menu bar does not display the previously uploaded file。Uploading errors can cause container crashes, and the web error output is as follows：
`Unknown Error {"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":"/webshark/upload","ok":false,"name":"HttpErrorResponse","message":"Http failure response for /webshark/upload: 0 Unknown Error","error":{"isTrusted":true}}`

**Comment by lmangani** [comment]
@shuimoshusheng make sure your volume has full read/write permissions. Most likely, it currently does not.

**Comment by shuimoshusheng** [comment]
> @shuimoshusheng make sure your volume has full read/write permissions. Most likely, it currently does not.
Without setting users and groups, the volume folder with permissions of 755 will report an error, while the volume  folder with permissions of 777 will not report an error，thank you very much！
