### ISSUE TITLE
Add Plugin Support

### ISSUE THREAD

**Issue by hamidrhashmi** [QXIP/webshark#35]
Can we add Plugin support in webshark ?

For example, if I want to add [HEP3 Dissector](https://github.com/sipcapture/hep-wireshark) in Webshark, how it can be done?

**Comment by YongBig** [comment]
I also have the same question .

**Comment by ekoyle** [comment]
It is possible that using the forked version of Wireshark when building webshark will work (it might not, but it should be relatively easy to test). 
Look in the webshark Dockerfile for the wireshark GitHub URL and try updating that to the one you are interested in.

**Comment by ekoyle** [comment]
I thought that was a fork of wireshark, but I see that it is just an external plugin. Rather than changing the URL for wireshark, you would need to add steps to the Dockerfile to build that plugin.

**Comment by lmangani** [comment]
I cannot find an explicit way for sharkd to load any plugins so far

**Comment by lmangani** [comment]
If anyone finds a way, please comment/reopen this issue anytime.
