### ISSUE TITLE
Cannot open capture

### ISSUE THREAD

**Issue by deanfourie1** [QXIP/webshark#36]
The capture uploads successfully, but then nothing happens, it just hangs on the upload screen.

Thanks

<img width="1364" alt="image" src="https://github.com/QXIP/webshark/assets/71812804/e8a64a43-69c2-4670-aa0d-da3e2c3daccc">

**Comment by lmangani** [comment]
Check the console for errors

**Comment by ekoyle** [comment]
It looks like permissions were not set for /captures in the Dockerfile.

There is also an issue with the way bind mounts are handled via docker compose. Manually changing the ownership on the captures directory to the correct UID:GID (1000:1000) should make it work with the existing `docker-compose.yml` .
