### ISSUE TITLE
pcapng file bug

### ISSUE THREAD

**Issue by asasasasasbc** [QXIP/webshark#43]
After uploading .pcapng file to webshark, once you click the web browser's refresh button, the web page will reset itself, going back to http://localhost:8085/webshark/ instead of http://localhost:8085/webshark/#XXXXXXXXXXXX and won't show the file's visualizing result again. 

In addition, copying the .pcapng file's visualization URL http://localhost:8085/webshark/#XXXXXXXXXXXX to another web tab will also be redirected to http://localhost:8085/webshark/

**Comment by lmangani** [comment]
Thanks for the report! This most likely means the file wasn't correctly uploaded and/or the format was not recognized. Only PCAP files are fully supported at this time and while others might work there are no warranties.
