### ISSUE TITLE
Small feature request!

### ISSUE THREAD

**Issue by deanfourie1** [QXIP/webshark#45]
Firstly, thanks so much for making this. It is so clean and the colors are perfect. This is such a handy little tool! Thanks so much!

One immediate thing I would suggest from using it twice now, is a little progress bar when a PCAP file is loading or being analyzed for display.

Thanks again!

**Comment by lmangani** [comment]
Thanks @deanfourie1 thanks for the kind words and for using our tool!

The next version introduces some major changes processing all packets in WASM. We'll try to add some indicators for the PCAP processing if there's a chance to do so.

**Comment by lmangani** [comment]
@RFbkak37y3kIY if viable, please keep this in mind for the future WASM version 😉

**Comment by deanfourie1** [comment]
Guys, is there any update to the progress of this?

Thanks

**Comment by lmangani** [comment]
@deanfourie1 we're busy with other projects at the moment but we'll sure get back to this in a couple months hopefully
